### PR TITLE
performance-tests: fixed module and default location for report data

### PR DESCRIPTION
**Pull request by ibek**

### CODE REVIEW

**Comment by mswiderski** [comment]
looks good to me - assuming that the reportData folder will be created in case it does not exists

**Comment by ibek** [comment]
yes, see the changes here https://github.com/ibek/droolsjbpm-integration/commit/4a3b52cd47a38b9d26ea4e0b387764f70e25a601#diff-6164e3420f8ae70a7b7f82640d4cb184R65

**Comment by mswiderski** [comment]
cool,

do you mind using this jira as reference when adding stuff for performance kit: https://issues.jboss.org/browse/JBPM-4682

**Comment by ibek** [comment]
ok, I will use the JIRA as reference

**Pull request merged**
